"""Provider sign-up instructions and key URLs."""

PROVIDER_GUIDES = {
    "openrouter": {
        "name": "OpenRouter",
        "sign_in_url": "https://openrouter.ai/keys",
        "docs_url": "https://openrouter.ai/docs",
        "env_key": "OPENROUTER_KEY",
        "rate_limit": "20 RPM, 200 RPD per free model",
        "instructions": [
            "Go to openrouter.ai and sign in with GitHub or Google",
            "Navigate to Keys page (openrouter.ai/keys)",
            'Click "Create Key"',
            "Copy the key (starts with sk-or-v1-)",
            "Paste it in your .env as OPENROUTER_KEY=sk-or-...",
        ],
        "notes": "Largest free model catalog. Free models have :free suffix. No credit card needed.",
    },
    "nvidia": {
        "name": "NVIDIA NIM",
        "sign_in_url": "https://build.nvidia.com/explore/discover",
        "docs_url": "https://docs.api.nvidia.com/nim/reference",
        "env_key": "NVIDIA_KEY",
        "rate_limit": "40 RPM, 1000 RPD",
        "instructions": [
            "Go to build.nvidia.com",
            "Click 'Sign In' (use GitHub, Google, or NVIDIA account)",
            "Join the NVIDIA Developer Program (free)",
            "Go to build.nvidia.com/settings/api-keys",
            'Click "Generate Key"',
            "Copy the key (starts with nvapi-)",
            "Paste it in your .env as NVIDIA_KEY=nvapi-...",
        ],
        "notes": "100+ models, no daily token cap. All models free on developer tier. Best free provider.",
    },
    "groq": {
        "name": "Groq",
        "sign_in_url": "https://console.groq.com/keys",
        "docs_url": "https://console.groq.com/docs",
        "env_key": "GROQ_KEY",
        "rate_limit": "30 RPM, 14,400 RPD",
        "instructions": [
            "Go to console.groq.com",
            "Sign up or log in with Google/GitHub",
            "Go to API Keys page (console.groq.com/keys)",
            'Click "Create API Key"',
            "Give it a name and copy the key (starts with gsk_)",
            "Paste it in your .env as GROQ_KEY=gsk_...",
        ],
        "notes": "Ultra-fast inference using LPU chips. Llama 4, DeepSeek, Qwen available. No credit card.",
    },
    "github": {
        "name": "GitHub Models",
        "sign_in_url": "https://github.com/marketplace/models",
        "docs_url": "https://docs.github.com/en/github-models",
        "env_key": "GITHUB_KEY",
        "rate_limit": "10-15 RPM, 50-150 RPD (varies by model)",
        "instructions": [
            "Go to github.com/settings/tokens",
            'Click "Generate new token (classic)"',
            "Give it a name (e.g. 'free-llm-gateway')",
            "No special scopes needed — just leave defaults",
            "Click Generate token",
            "Copy the token (starts with ghp_)",
            "Paste it in your .env as GITHUB_KEY=ghp_...",
        ],
        "notes": "Access to gpt-4.1, o3-mini, o4-mini, Llama 4, DeepSeek R1. Free for all GitHub users.",
    },
    "cerebras": {
        "name": "Cerebras",
        "sign_in_url": "https://cloud.cerebras.ai/",
        "docs_url": "https://cloud.cerebras.ai/docs",
        "env_key": "CEREBRAS_KEY",
        "rate_limit": "30 RPM, 1M tokens/day",
        "instructions": [
            "Go to cloud.cerebras.ai",
            "Sign up (free, no credit card)",
            "After email verification, log in",
            "Go to API Keys in your dashboard",
            "Copy your API key (starts with csk-)",
            "Paste it in your .env as CEREBRAS_KEY=csk-...",
        ],
        "notes": "Fastest inference (~2,600 tokens/sec). Llama models only. No credit card needed.",
    },
    "google_gemini": {
        "name": "Google Gemini",
        "sign_in_url": "https://aistudio.google.com/apikey",
        "docs_url": "https://ai.google.dev/gemini-api/docs",
        "env_key": "GOOGLE_GEMINI_KEY",
        "rate_limit": "10-15 RPM, 250-1000 RPD",
        "instructions": [
            "Go to aistudio.google.com/apikey",
            "Sign in with your Google account",
            'Click "Create API Key"',
            "Select a Google Cloud project (or create one)",
            "Copy the API key",
            "Paste it in your .env as GOOGLE_GEMINI_KEY=AIza...",
        ],
        "notes": "Gemini 2.5 Flash with 1M context. Free tier NOT available in EU/UK/Switzerland. Google may use prompts to improve products.",
    },
    "mistral": {
        "name": "Mistral AI",
        "sign_in_url": "https://console.mistral.ai/api-keys",
        "docs_url": "https://docs.mistral.ai",
        "env_key": "MISTRAL_KEY",
        "rate_limit": "~1 RPS, 500K TPM",
        "instructions": [
            "Go to console.mistral.ai",
            "Sign up (free, no credit card)",
            "After email verification, log in",
            "Go to API Keys (console.mistral.ai/api-keys)",
            'Click "Create new key"',
            "Copy the key",
            "Paste it in your .env as MISTRAL_KEY=...",
        ],
        "notes": "~1 billion tokens/month on free 'Experiment' plan. Mistral Small 4, Medium 3, Large 3, Codestral available.",
    },
    "cohere": {
        "name": "Cohere",
        "sign_in_url": "https://dashboard.cohere.com/api-keys",
        "docs_url": "https://docs.cohere.com",
        "env_key": "COHERE_KEY",
        "rate_limit": "20 RPM, 1000 calls/month",
        "instructions": [
            "Go to dashboard.cohere.com",
            "Sign up (free trial, no credit card)",
            "After verification, go to API Keys",
            "Copy your trial key",
            "Paste it in your .env as COHERE_KEY=...",
        ],
        "notes": "Command A (111B), Command R+, Command R, R7B. 1000 API calls/month. Non-commercial use only on trial.",
    },
    "siliconflow": {
        "name": "SiliconFlow",
        "sign_in_url": "https://cloud.siliconflow.cn/account/ak",
        "docs_url": "https://docs.siliconflow.cn",
        "env_key": "SILICONFLOW_KEY",
        "rate_limit": "1000 RPM, 50K TPM",
        "instructions": [
            "Go to cloud.siliconflow.cn",
            "Sign up (phone or email)",
            "You get 14 CNY signup credits (free)",
            "Go to Account → API Keys",
            'Click "Create API Key"',
            "Copy the key (starts with sk-)",
            "Paste it in your .env as SILICONFLOW_KEY=sk-...",
        ],
        "notes": "Qwen3-8B, DeepSeek R1, GLM-4 models. Permanently free models available. Very generous rate limits.",
    },
    "huggingface": {
        "name": "Hugging Face",
        "sign_in_url": "https://huggingface.co/settings/tokens",
        "docs_url": "https://huggingface.co/docs/api-inference",
        "env_key": "HUGGINGFACE_KEY",
        "rate_limit": "~1000 RPD",
        "instructions": [
            "Go to huggingface.co and create an account",
            "Go to Settings → Access Tokens",
            'Click "New token"',
            "Give it a name, select 'Read' access",
            "Copy the token (starts with hf_)",
            "Paste it in your .env as HUGGINGFACE_KEY=hf_...",
        ],
        "notes": "Thousands of community models. Free serverless inference + $0.10/month free credits for dedicated endpoints.",
    },
    "cloudflare": {
        "name": "Cloudflare Workers AI",
        "sign_in_url": "https://dash.cloudflare.com/profile/api-tokens",
        "docs_url": "https://developers.cloudflare.com/workers-ai",
        "env_key": "CLOUDFLARE_KEY",
        "rate_limit": "10K neurons/day",
        "instructions": [
            "Go to dash.cloudflare.com and create an account (free)",
            "Go to Profile → API Tokens",
            'Click "Create Token"',
            "Select 'Custom token' or use Workers AI template",
            "Set permissions: Workers AI → Read",
            "Copy the token",
            "Also copy your Account ID from the URL",
            "Paste in .env: CLOUDFLARE_KEY=your-token",
            "And: CLOUDFLARE_ACCOUNT_ID=your-account-id",
        ],
        "notes": "50+ models including Llama 4 Scout, Gemma 4, Mistral, DeepSeek R1. 10K neurons/day free.",
    },
    "llm7": {
        "name": "LLM7",
        "sign_in_url": "https://token.llm7.io",
        "docs_url": "https://llm7.io",
        "env_key": "LLM7_KEY",
        "rate_limit": "30 RPM (120 with token)",
        "instructions": [
            "Go to token.llm7.io",
            "No registration needed for basic access!",
            "Optional: get a token for higher rate limits (120 RPM)",
            "Paste token in .env as LLM7_KEY=... (or leave empty for basic access)",
        ],
        "notes": "Zero-friction gateway. No registration needed. DeepSeek R1, V3, GPT-4o-mini, Qwen, and more.",
    },
    "ollama": {
        "name": "Ollama Cloud",
        "sign_in_url": "https://ollama.com/settings/keys",
        "docs_url": "https://docs.ollama.com/cloud",
        "env_key": "OLLAMA_KEY",
        "rate_limit": "Session/weekly limits (unpublished)",
        "instructions": [
            "Go to ollama.com and create an account",
            "Go to Settings → Keys",
            "Generate an API key",
            "Paste in .env as OLLAMA_KEY=...",
        ],
        "notes": "400+ models from Ollama library. Free tier with qualitative limits. NOT OpenAI SDK-compatible (uses Ollama API).",
    },
    "local": {
        "name": "Local LLM",
        "sign_in_url": "https://ollama.com",
        "docs_url": "https://github.com/ollama/ollama/blob/main/docs/openai.md",
        "env_key": "LOCAL_LLM_MODEL",
        "rate_limit": "Unlimited (local hardware)",
        "instructions": [
            "Run a local OpenAI-compatible server (Ollama, LM Studio, llama.cpp, vLLM, etc.)",
            "Set LOCAL_LLM_BASE_URL (default: http://127.0.0.1:11434/v1 for Ollama)",
            "Set LOCAL_LLM_MODEL to a model id your local server exposes (e.g. llama3.2)",
            "Optional: LOCAL_LLM_KEY if your server requires auth",
        ],
        "notes": "Last-resort fallback appended to every model chain. Only used after all cloud providers fail.",
    },
    "kilo_code": {
        "name": "Kilo AI",
        "sign_in_url": "https://kilo.ai",
        "docs_url": "https://docs.kilo.ai",
        "env_key": "KILO_KEY",
        "rate_limit": "~200 req/hr",
        "instructions": [
            "Go to kilo.ai and sign up",
            "Navigate to API settings",
            "Generate an API key",
            "Paste in .env as KILO_KEY=...",
        ],
        "notes": "Auto-routes to best free models (MiniMax M2.5, Step-3.5 Flash). 200 requests/hour.",
    },
    "zhipu": {
        "name": "Zhipu AI (GLM)",
        "sign_in_url": "https://open.bigmodel.cn/usercenter/apikeys",
        "docs_url": "https://open.bigmodel.cn/dev/api",
        "env_key": "ZHIPU_KEY",
        "rate_limit": "1 concurrent request",
        "instructions": [
            "Go to open.bigmodel.cn",
            "Sign up (phone verification required)",
            "Go to User Center → API Keys",
            "Generate a key",
            "Paste in .env as ZHIPU_KEY=...",
        ],
        "notes": "GLM-4.7-Flash (200K context), GLM-4.5-Flash, GLM-4.6V-Flash (vision). Permanently free, no card needed.",
    },
    "modelscope": {
        "name": "ModelScope",
        "sign_in_url": "https://modelscope.cn/my/myaccesstoken",
        "docs_url": "https://modelscope.cn/docs",
        "env_key": "MODELSCOPE_KEY",
        "rate_limit": "2000 RPD total, ≤500 per model",
        "instructions": [
            "Go to modelscope.cn and create an account",
            "Requires Alibaba Cloud account binding + real-name verification",
            "Go to My AccessToken page",
            "Copy your access token",
            "Paste in .env as MODELSCOPE_KEY=...",
        ],
        "notes": "Qwen models, image generation. Requires Alibaba Cloud account. 2000 requests/day shared across models.",
    },
}


def get_all_guides():
    """Return all provider guides."""
    return PROVIDER_GUIDES


def get_guide(provider_name: str):
    """Return guide for a specific provider."""
    return PROVIDER_GUIDES.get(provider_name)
